import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Menu } from "lucide-react"


const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex-1">
      <section className="bg-primary py-12 px-6 md:px-12 flex flex-col items-center justify-center">
        <h1 className="text-3xl md:text-5xl font-bold text-primary-foreground mb-4">
          Discover the World with Explore
        </h1>
        <p className="text-lg md:text-xl text-primary-foreground mb-8">
          Find the perfect tours, hotels, and transportation for your next adventure.
        </p>
        <div className="w-full max-w-3xl">
          <Input
            type="search"
            placeholder="Search for tours, hotels, or transportation"
            className="w-full rounded-full px-6 py-3 text-lg"
          />
        </div>
      </section>
      {children}
    </main>
      
  );
}
