import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Menu } from "lucide-react"


const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
					<div className="text-2xl font-bold">Explore</div>
					<nav className="hidden md:flex items-center gap-6">
						<Link href="/tours" className="hover:underline" prefetch={false}>
							Tours
						</Link>
						<Link href="/accommodations" className="hover:underline" prefetch={false}>
							Accommodation
						</Link>
						<Link href="/transports" className="hover:underline" prefetch={false}>
							Transportation
						</Link>
						<Link href="/reservations" className="hover:underline" prefetch={false}>
							Reservations
						</Link>

					</nav>
					<Button variant="ghost" size="icon" className="md:hidden">
						<Menu />
					</Button>
				</header>
				{children}
				<footer className="bg-primary text-primary-foreground py-6 px-6 flex items-center justify-between">
					<div className="text-sm">&copy; 2023 Explore. All rights reserved.</div>
					<nav className="hidden md:flex items-center gap-6">
						<Link href="#" className="hover:underline" prefetch={false}>
							Terms of Service
						</Link>
						<Link href="#" className="hover:underline" prefetch={false}>
							Privacy Policy
						</Link>
						<Link href="#" className="hover:underline" prefetch={false}>
							FAQ
						</Link>
					</nav>
				</footer>
			</body>
		</html>
	);
}
